### ISSUE TITLE
Clarity on permissions/multi-sig

### ISSUE THREAD

**Issue by gichiba** [JoinColony/colonyJS#241] opened 2018-07-16 08:17 UTC
There are some callers and senders such as `setTaskRoleUser.send({ taskId, role, user }, options)` that do not specify who may and may not send the transaction, or what additional signatures would be required for the operation to pass. 

This could be clarified in the API/commenting, and could also be added in the multi-sig documentation in a table of some sort.

**Comment by gichiba** [comment] 2018-07-16 08:56
oh. this might be the same as #217 ...

**Comment by ryanchristo** [comment] 2018-11-29 16:24
Duplicate of #217

**Closed by ryanchristo** 2018-11-29 16:24 UTC
